### ISSUE TITLE
关于「学习学习：知识管理工具」的几点疑问？

### ISSUE THREAD

**Issue by JimmyLv** [lyricat/lyric.im#1]
[[source/_posts/learn-to-learn-tools.md]]

首先感谢这篇文章，非常棒！
1. 想问下里面的图片是用什么画的呢？
2. 有没有什么办法可以让DEVONthink索引Anki里面的内容？

![image](https://user-images.githubusercontent.com/4997466/69122101-e76b3d00-0ad8-11ea-8561-810ff4649610.png)

**Comment by lyricat** [comment]
用 keynote 画的。暂时没什么办法让 devonthink 索引 anki 的内容
